CLIENT_SOCKET_PORT = 27019
SERVER_IP = '192.168.0.22'

REQUEST='request'
RESPONSE='response'
SUBSCRIBE='subscribe'
COLLECTOR='collector'
SUBSCRIBE_RESPONSE='sresponse'

MARKET_STOCK = 'stock'


DAY_DATA = 'day_data'
STOCK_DATA = 'stock_realtime'
BACK_DATA = 'stock_backdata'
COLLECTOR_DATA = 'collector_data'


CAPABILITY_REQUEST_RESPONSE=1
CAPABILITY_COLLECT_SUBSCRIBE=2
CAPABILITY_TRADE=4
