# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import stock_provider_pb2 as stock__provider__pb2


class StockStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetDayData = channel.unary_unary(
        '/stock_api.Stock/GetDayData',
        request_serializer=stock__provider__pb2.StockQuery.SerializeToString,
        response_deserializer=stock__provider__pb2.CybosDayDatas.FromString,
        )
    self.GetMinuteData = channel.unary_unary(
        '/stock_api.Stock/GetMinuteData',
        request_serializer=stock__provider__pb2.StockQuery.SerializeToString,
        response_deserializer=stock__provider__pb2.CybosDayDatas.FromString,
        )
    self.SubscribeStock = channel.unary_stream(
        '/stock_api.Stock/SubscribeStock',
        request_serializer=stock__provider__pb2.StockCodeQuery.SerializeToString,
        response_deserializer=stock__provider__pb2.CybosTickData.FromString,
        )
    self.SubscribeBidAsk = channel.unary_stream(
        '/stock_api.Stock/SubscribeBidAsk',
        request_serializer=stock__provider__pb2.StockCodeQuery.SerializeToString,
        response_deserializer=stock__provider__pb2.CybosBidAskTickData.FromString,
        )


class StockServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetDayData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMinuteData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubscribeStock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubscribeBidAsk(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StockServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetDayData': grpc.unary_unary_rpc_method_handler(
          servicer.GetDayData,
          request_deserializer=stock__provider__pb2.StockQuery.FromString,
          response_serializer=stock__provider__pb2.CybosDayDatas.SerializeToString,
      ),
      'GetMinuteData': grpc.unary_unary_rpc_method_handler(
          servicer.GetMinuteData,
          request_deserializer=stock__provider__pb2.StockQuery.FromString,
          response_serializer=stock__provider__pb2.CybosDayDatas.SerializeToString,
      ),
      'SubscribeStock': grpc.unary_stream_rpc_method_handler(
          servicer.SubscribeStock,
          request_deserializer=stock__provider__pb2.StockCodeQuery.FromString,
          response_serializer=stock__provider__pb2.CybosTickData.SerializeToString,
      ),
      'SubscribeBidAsk': grpc.unary_stream_rpc_method_handler(
          servicer.SubscribeBidAsk,
          request_deserializer=stock__provider__pb2.StockCodeQuery.FromString,
          response_serializer=stock__provider__pb2.CybosBidAskTickData.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'stock_api.Stock', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
